export { apiClient, ApiRequestError } from './client'
export { labNotesService } from './labNotes'
export { projectsService } from './projects'
export { categoriesService } from './categories'
export { contactService } from './contact'
export { authService } from './auth'
export { adminLabNotesService } from './adminLabNotes'
export { adminProjectsService } from './adminProjects'
export { adminCategoriesService } from './adminCategories'
export { uploadService } from './upload'
export { adminAutocompleteService } from './adminAutocomplete'
export type { LoginCredentials, AuthResponse } from './auth'
export type { Suggestion, SuggestionOutcome } from './adminAutocomplete'
export type { CreateLabNoteData, UpdateLabNoteData } from './adminLabNotes'
export type { CreateProjectData, UpdateProjectData } from './adminProjects'
