export { apiClient, ApiRequestError } from './client'
export { labNotesService } from './labNotes'
export { projectsService } from './projects'
export { contactService } from './contact'
export { authService } from './auth'
export { adminLabNotesService } from './adminLabNotes'
export { adminProjectsService } from './adminProjects'
export type { LoginCredentials, AuthResponse } from './auth'
export type { CreateLabNoteData, UpdateLabNoteData } from './adminLabNotes'
export type { CreateProjectData, UpdateProjectData } from './adminProjects'
